### ISSUE TITLE
Change level 14 place

### ISSUE THREAD

**Issue by Uriopass** [sharkdp/curiosity#13]
I think level 14 is far too easy compared to the torus / rainbow levels.

**Comment by sharkdp** [comment]
Agreed, yes. Thanks for the comment.

Unfortunately, moving a level involves manually moving all files to different folders and some renaming... I'll try to look into a better solution.

**Comment by Uriopass** [comment]
Maybe something like a python script to generate the levels based on the templates
In pseudo-python-script this could look like this :
```python
def createTemplate(path, number):
    dir_name = "levels/level{}".format(leftpad(number, 3)) # 3 becomes levels/level003
    makedir(dir_name)
    copyfiles(path, dir_name) # thoses functions dont exist, its just to explain
sortdict = {'blob': 1; 'compass': 2} # key is name, value is complexity
sortdict.sortbyvalue()
for key,value in sortdict.items():
    createTemplate("templates/{}".format(key), value)
```

**Comment by sharkdp** [comment]
Exactly! Plus, the links to the next level would have to be auto-generated from the map. Concerning `sortdict`, I'd probably just use a list of levels `['blob', 'compass', ...]`. Thanks for the suggestion!

**Comment by sharkdp** [comment]
Closing this in trying to clean my long list of open tickets. Feel free to comment here if you think that this is still relevant, so that the ticket can be reopened.
