### ISSUE TITLE
Rethink the CSV level

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/curiosity#16]
- A lot of people seem to dislike it
- It stands out, since it cannot (easily) be solved from within the browser (well... later levels cannot be solved from the browser either)

**Comment by Uriopass** [comment]
I think it's great but you could plot less points and "connect" them to make a real shape rather than a geometrical shape (like a smiley or something).

**Comment by dnlosx** [comment]
Actually I used the browser to solve it (easily):
http://bl.ocks.org/phil-pedruco/9913243

I searched 'csv to 3d' in Google.

**Comment by codec-abc** [comment]
I think it's great too. And using webgl it can be solved pretty easily in a web browser even if I solved it using blender. Writing the full javascript code to get the point cloud rendered might be tedious but if you provide some sort of script it should be enough (maybe put some holes to be completed by the user so it won't become too easy).

**Comment by sharkdp** [comment]
Thank you for your comments. I think I'll leave the issue open, in case someone comes up with a much better idea than the current implementation.

**Comment by rybak** [comment]
For the record, this is what I got by running `splot 'shape.csv' with lines` in gnuplot: [spoiler](https://user-images.githubusercontent.com/624072/143664926-cfbe967b-4372-484f-9a3d-ede61f04c03f.png). After rotating the shape a little, I just guessed the answer. Got it on the third try after U+1F9C0 and U+1F6DE.

**Comment by sharkdp** [comment]
> Got it on the third try after U+1F9C0 and U+1F6DE.

:smile:

**Comment by MagicalDrizzle** [comment]
I feel like I definitely overthought this a lot, I finally used matplotlib after spending half an hour googling "3D coordinate to plot" lol

**Comment by benwaffle** [comment]
This one was fun. I just asked v0.dev (an AI tool) to build me a 3d point plotter - https://v0.dev/chat/3-d-csv-plotter-tL2gzrtP2Oy
