### ISSUE TITLE
Shouldn't level10 answer be different?

### ISSUE THREAD

**Issue by krisztian-kapitany** [sharkdp/curiosity#17]
Maybe I am not getting why this is
fever.html (high body temperature) -> fewer.html (as in "less than")

**Comment by sharkdp** [comment]
Hm... how did you arrive at `fever.html` in the first place? This is already the solution....

**Comment by krisztian-kapitany** [comment]
yes, 'fever' is the solution, but shouldn't it be 'fewer'?

**Comment by sharkdp** [comment]
I don't see how you would arrive at the answer `fewer.html` from the starting page of level 10: https://shark.fish/curiosity/level010/at_symbol.html

**Comment by krisztian-kapitany** [comment]
Ok, I'm just not getting it then :) Awesome puzzles though!

**Comment by Corgile** [comment]
But why fever?

**Comment by sharkdp** [comment]
> But why fever?

Well, if you want to be spoiled (and if you want to know why I think this puzzle should be changed), you can click here:

<details>
<summary>Spoiler</summary>

The @ symbol is an indication that `curiosity314` is a twitter handle. If you go to https://twitter.com/curiosity314, you should see a tweet with the puzzle solution.

Unfortunately, Twitter is behind a login wall nowadays. So I think this puzzle should be changed / removed.
</details>
