### ISSUE TITLE
Level 13 solution case sensitivity

### ISSUE THREAD

**Issue by dmringo** [sharkdp/curiosity#23]
Despite the presence of both upper and lower cased file names for the solution in the level013 directory here, it seems that the lower case URL isn't being handled properly at the moment. Seems repeatable across every browser I try, curl/wget, etc.

**Comment by rybak** [comment]
This seems to be an issue with the HTTP server being used. When running a Python's `http.server` module locally:

```sh
$ ./deploy.sh && cd dist/ && python -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
```

... both lowercase and uppercase work:
<details>
  <summary>Spoiler warning</summary>

![image](https://user-images.githubusercontent.com/624072/155865220-cd66c109-f193-4be0-a328-58970e524a3f.png)

![image](https://user-images.githubusercontent.com/624072/155865217-29928dc8-a7d6-4cc0-b531-088cd1f9d60d.png)
</details>

**Comment by dmringo** [comment]
hmm, that's interesting. I'm having a hard time imagining what might make the server treat the URL case-sensitively, but somehow not respond with either of the upper/lower case solutions. Case-insensitive filesystem playing tricks somehow?

Another data point: the lower case solution for level 12 seems to work, but not the upper case (again, despite both in the tree here).

**Comment by sharkdp** [comment]
Thank you for reporting this. Turns out it was `dropbox` which "helpfully" renamed the lowercase file to something like `1f308 (Case conflict).html` :angry: (https://help.dropbox.com/installs-integrations/sync-uploads/case-conflict)

Should work now.

https://shark.fish/curiosity/level013/1f308.html
