### ISSUE TITLE
Should this be public?

### ISSUE THREAD

**Issue by bijection** [sharkdp/curiosity#9]
It seems to me that this repo might be a bit too easy for puzzlers to find prematurely.

What if you made it private, or changed its name / hosted it under a different user to make it more obscure?

**Comment by naveenarun** [comment]
+1 for this

**Comment by sharkdp** [comment]
Thank you for the message.

I was thinking about this for quite some time, before uploading the code to GitHub. I would somehow like the project to be open so people can contribute easily by just sending a PR. I tried to add spoiler warnings in the relevant places (inside the `levels` folder). Do you think that the spoiler warnings should be even more apparent (like having to click through multiple nested folders with warning messages on each level), or would you remove the code from GitHub completely?

If I just make the repository harder to find, that will not prevent people from attempting to 'cheat'. I guess the repository could still easily be found through a GitHub search. It will probably just make it harder for possible contributers.

My hope was that people who really enjoy the game would refrain from looking into the solutions. But I understand that the temptation might be there, if there is the possibility.

**Comment by gileswells** [comment]
I do like the repo being here cause I can star it and know when newer levels have been merged in. That being said its also nice to be able to cheat in case I really don't have a damn clue as to the answer and just want to move onward to the next newer level.
